//! Beamer/LaTeX exporter for presentations
const std = @import("std");
const Presentation = @import("../core/Presentation.zig").Presentation;
const Slide = @import("../core/Slide.zig").Slide;
const Element = @import("../core/Element.zig").Element;
const inlineToPlainText = @import("../core/Element.zig").inlineToPlainText;

/// Beamer/LaTeX exporter for generating LaTeX beamer presentations
pub const BeamerExporter = struct {
    allocator: std.mem.Allocator,
    theme: ?[]const u8,
    color_theme: ?[]const u8,

    const Self = @This();

    /// Available Beamer themes
    pub const Theme = enum {
        default,
        classic,
        metropolis,
        berlin,
        warsaw,
        madrid,
        frankfurt,
        singapore,
        szeged,
        cambridgeus,

        pub fn toString(self: Theme) []const u8 {
            return switch (self) {
                .default => "default",
                .classic => "classic",
                .metropolis => "metropolis",
                .berlin => "berlin",
                .warsaw => "warsaw",
                .madrid => "madrid",
                .frankfurt => "frankfurt",
                .singapore => "singapore",
                .szeged => "szeged",
                .cambridgeus => "cambridgeus",
            };
        }
    };

    pub fn init(allocator: std.mem.Allocator, theme: ?[]const u8, color_theme: ?[]const u8) Self {
        return .{
            .allocator = allocator,
            .theme = theme,
            .color_theme = color_theme,
        };
    }

    /// Export presentation to LaTeX/Beamer string
    pub fn exportToLatex(self: Self, presentation: Presentation) ![]const u8 {
        var output: std.ArrayList(u8) = .empty;
        defer output.deinit(self.allocator);
        const writer = output.writer(self.allocator);

        try self.writePreamble(writer, presentation);
        try self.writeDocumentStart(writer);

        // Title slide
        try writer.writeAll("\\begin{frame}\n");
        try writer.writeAll("    \\titlepage\n");
        try writer.writeAll("\\end{frame}\n\n");

        // Content slides
        for (presentation.slides) |slide| {
            try self.writeSlide(writer, slide);
        }

        try self.writeDocumentEnd(writer);

        return output.toOwnedSlice(self.allocator);
    }

    /// Export presentation to LaTeX file
    pub fn exportToFile(self: Self, presentation: Presentation, path: []const u8) !void {
        const latex = try self.exportToLatex(presentation);
        defer self.allocator.free(latex);

        const file = try std.fs.cwd().createFile(path, .{});
        defer file.close();

        try file.writeAll(latex);
    }

    fn writePreamble(self: Self, writer: anytype, presentation: Presentation) !void {
        try writer.writeAll("% Beamer presentation generated by TUIA\n");
        try writer.writeAll("% Compile with: pdflatex presentation.tex\n\n");

        try writer.writeAll("\\documentclass[aspectratio=169]{beamer}\n\n");

        // Theme configuration
        const beamer_theme = self.theme orelse "default";
        try writer.writeAll("\\usetheme{");
        try writer.writeAll(beamer_theme);
        try writer.writeAll("}\n");

        if (self.color_theme) |ct| {
            try writer.writeAll("\\usecolortheme{");
            try writer.writeAll(ct);
            try writer.writeAll("}\n");
        }

        // Packages
        try writer.writeAll("\n% Required packages\n");
        try writer.writeAll("\\usepackage[utf8]{inputenc}\n");
        try writer.writeAll("\\usepackage[T1]{fontenc}\n");
        try writer.writeAll("\\usepackage{lmodern}\n");
        try writer.writeAll("\\usepackage{graphicx}\n");
        try writer.writeAll("\\usepackage{listings}\n");
        try writer.writeAll("\\usepackage{booktabs}\n");
        try writer.writeAll("\\usepackage{hyperref}\n\n");

        // Code listing settings
        try writer.writeAll("% Code listing settings\n");
        try writer.writeAll("\\lstset{\n");
        try writer.writeAll("    basicstyle=\\ttfamily\\small,\n");
        try writer.writeAll("    breaklines=true,\n");
        try writer.writeAll("    frame=single,\n");
        try writer.writeAll("    showstringspaces=false\n");
        try writer.writeAll("}\n\n");

        // Document metadata
        if (presentation.metadata.title) |title| {
            try writer.writeAll("\\title{");
            try writeEscapedLatex(writer, title);
            try writer.writeAll("}\n");
        }

        if (presentation.metadata.author) |author| {
            try writer.writeAll("\\author{");
            try writeEscapedLatex(writer, author);
            try writer.writeAll("}\n");
        }

        if (presentation.metadata.date) |date| {
            try writer.writeAll("\\date{");
            try writeEscapedLatex(writer, date);
            try writer.writeAll("}\n");
        } else {
            try writer.writeAll("\\date{\\today}\n");
        }

        try writer.writeAll("\n");
    }

    fn writeDocumentStart(_: Self, writer: anytype) !void {
        try writer.writeAll("\\begin{document}\n\n");
    }

    fn writeDocumentEnd(_: Self, writer: anytype) !void {
        try writer.writeAll("\\end{document}\n");
    }

    fn writeSlide(self: Self, writer: anytype, slide: Slide) !void {
        // Extract title from first heading if present
        var slide_title: ?[]const u8 = null;
        for (slide.elements) |element| {
            if (element == .heading) {
                slide_title = try inlineToPlainText(self.allocator, element.heading.content);
                break;
            }
        }

        try writer.writeAll("\\begin{frame}");
        if (slide_title) |title| {
            defer self.allocator.free(title);
            try writer.writeAll("{");
            try writeEscapedLatex(writer, title);
            try writer.writeAll("}");
        }
        try writer.writeAll("\n");

        for (slide.elements) |element| {
            try self.writeElement(writer, element);
        }

        try writer.writeAll("\\end{frame}\n\n");
    }

    fn writeElement(self: Self, writer: anytype, element: Element) !void {
        switch (element) {
            .heading => |h| {
                // Skip h1 as it's used for slide title
                if (h.level > 1) {
                    const text = try inlineToPlainText(self.allocator, h.content);
                    defer self.allocator.free(text);
                    try writer.writeAll("    \\textbf{");
                    try writeEscapedLatex(writer, text);
                    try writer.writeAll("}\\par\n\n");
                }
            },
            .paragraph => |p| {
                try writer.writeAll("    ");
                try self.writeInlines(writer, p.content);
                try writer.writeAll("\\par\n\n");
            },
            .code_block => |cb| {
                try writer.writeAll("    \\begin{lstlisting}");
                if (cb.language) |lang| {
                    try writer.writeAll("[language=");
                    try writer.writeAll(mapLanguageToLatex(lang));
                    try writer.writeAll("]");
                }
                try writer.writeAll("\n");
                try writer.writeAll(cb.code);
                try writer.writeAll("\n    \\end{lstlisting}\n\n");
            },
            .list => |list| {
                const env = if (list.ordered) "enumerate" else "itemize";
                try writer.writeAll("    \\begin{");
                try writer.writeAll(env);
                try writer.writeAll("}\n");

                for (list.items) |item| {
                    try writer.writeAll("        \\item ");
                    try self.writeInlines(writer, item.content);
                    try writer.writeAll("\n");
                }

                try writer.writeAll("    \\end{");
                try writer.writeAll(env);
                try writer.writeAll("}\n\n");
            },
            .blockquote => |bq| {
                const text = try inlineToPlainText(self.allocator, bq.content);
                defer self.allocator.free(text);
                try writer.writeAll("    \\begin{quote}\n");
                try writer.writeAll("        ");
                try writeEscapedLatex(writer, text);
                try writer.writeAll("\n");
                try writer.writeAll("    \\end{quote}\n\n");
            },
            .thematic_break => {
                try writer.writeAll("    \\hrulefill\\par\n\n");
            },
            .image => |img| {
                try writer.writeAll("    \\begin{center}\n");
                try writer.writeAll("        \\includegraphics[width=0.8\\textwidth]{");
                try writer.writeAll(img.url);
                try writer.writeAll("}\n");
                try writer.writeAll("    \\end{center}\n\n");
            },
            .table => |t| {
                const col_count = t.headers.len;

                try writer.writeAll("    \\begin{center}\n");
                try writer.writeAll("    \\begin{tabular}{");
                for (0..col_count) |_| {
                    try writer.writeAll("l");
                }
                try writer.writeAll("}\n");
                try writer.writeAll("        \\toprule\n");

                // Headers
                for (t.headers, 0..) |header, i| {
                    try self.writeInlines(writer, header.content);
                    if (i < t.headers.len - 1) {
                        try writer.writeAll(" & ");
                    } else {
                        try writer.writeAll(" \\\\\n");
                    }
                }
                try writer.writeAll("        \\midrule\n");

                // Rows
                for (t.rows) |row| {
                    for (row, 0..) |cell, i| {
                        try self.writeInlines(writer, cell.content);
                        if (i < row.len - 1) {
                            try writer.writeAll(" & ");
                        } else {
                            try writer.writeAll(" \\\\\n");
                        }
                    }
                }

                try writer.writeAll("        \\bottomrule\n");
                try writer.writeAll("    \\end{tabular}\n");
                try writer.writeAll("    \\end{center}\n\n");
            },
            .media => |m| {
                // Media in LaTeX - use href for audio/video links
                try writer.writeAll("    \\begin{center}\n");
                try writer.print("        \\href{{{s}}}{{", .{m.url});
                if (m.title) |title| {
                    try writer.print("[{s}: {s}]", .{ @tagName(m.media_type), title });
                } else {
                    try writer.print("[{s}]", .{@tagName(m.media_type)});
                }
                try writer.writeAll("}\n");
                try writer.writeAll("    \\end{center}\n\n");
            },
        }
    }

    fn writeInlines(self: Self, writer: anytype, inlines: []const @import("../core/Element.zig").Inline) !void {
        for (inlines) |inline_elem| {
            switch (inline_elem) {
                .text => |t| try writeEscapedLatex(writer, t),
                .code => |c| {
                    try writer.writeAll("\\texttt{");
                    try writeEscapedLatex(writer, c);
                    try writer.writeAll("}");
                },
                .bold => |b| {
                    try writer.writeAll("\\textbf{");
                    try self.writeInlines(writer, b);
                    try writer.writeAll("}");
                },
                .italic => |i| {
                    try writer.writeAll("\\textit{");
                    try self.writeInlines(writer, i);
                    try writer.writeAll("}");
                },
                .link => |l| {
                    try writer.writeAll("\\href{");
                    try writer.writeAll(l.url);
                    try writer.writeAll("}{");
                    try self.writeInlines(writer, l.content);
                    try writer.writeAll("}");
                },
                .image => |img| {
                    try writer.writeAll("\\includegraphics[width=0.5\\textwidth]{");
                    try writer.writeAll(img.url);
                    try writer.writeAll("}");
                },
            }
        }
    }
};

/// Map common language names to LaTeX listings language names
fn mapLanguageToLatex(lang: []const u8) []const u8 {
    const map = .{
        .{ "zig", "C" },
        .{ "javascript", "JavaScript" },
        .{ "typescript", "TypeScript" },
        .{ "python", "Python" },
        .{ "rust", "Rust" },
        .{ "go", "Go" },
        .{ "c", "C" },
        .{ "cpp", "C++" },
        .{ "java", "Java" },
        .{ "bash", "bash" },
        .{ "shell", "bash" },
        .{ "sh", "bash" },
        .{ "yaml", "YAML" },
        .{ "json", "JSON" },
        .{ "markdown", "Markdown" },
        .{ "latex", "TeX" },
    };

    inline for (map) |entry| {
        if (std.mem.eql(u8, lang, entry[0])) {
            return entry[1];
        }
    }

    return lang;
}

/// Write text with LaTeX escaping
fn writeEscapedLatex(writer: anytype, text: []const u8) !void {
    for (text) |c| {
        switch (c) {
            '\\' => try writer.writeAll("\\textbackslash{}"),
            '{' => try writer.writeAll("\\{"),
            '}' => try writer.writeAll("\\}"),
            '$' => try writer.writeAll("\\$"),
            '&' => try writer.writeAll("\\&"),
            '#' => try writer.writeAll("\\#"),
            '^' => try writer.writeAll("\\^{}"),
            '_' => try writer.writeAll("\\_"),
            '%' => try writer.writeAll("\\%"),
            '~' => try writer.writeAll("\\textasciitilde{}"),
            '<' => try writer.writeAll("\\textless{}"),
            '>' => try writer.writeAll("\\textgreater{}"),
            else => try writer.writeByte(c),
        }
    }
}

// ============== Tests ==============

test "BeamerExporter basic structure" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "Test Presentation"),
            .author = try allocator.dupe(u8, "Test Author"),
            .date = try allocator.dupe(u8, "2026-03-03"),
            .theme = null,
        },
        .slides = try allocator.alloc(Slide, 1),
    };
    defer {
        presentation.metadata.deinit(allocator);
        for (presentation.slides) |slide| {
            slide.deinit(allocator);
        }
        allocator.free(presentation.slides);
    }

    var elements: std.ArrayList(Element) = .empty;
    defer elements.deinit(allocator);

    const heading_content = try allocator.alloc(@import("../core/Element.zig").Inline, 1);
    heading_content[0] = .{ .text = try allocator.dupe(u8, "Hello World") };

    try elements.append(allocator, .{ .heading = .{
        .content = heading_content,
        .level = 1,
    } });

    presentation.slides[0] = Slide{
        .elements = try elements.toOwnedSlice(allocator),
        .speaker_notes = null,
    };

    var exporter = BeamerExporter.init(allocator, null, null);
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    // Check basic structure
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\documentclass"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\begin{document}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\end{document}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\begin{frame}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\end{frame}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "Test Presentation"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "Test Author"));
}

test "BeamerExporter LaTeX escaping" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "Special $100 & 50% off"),
            .author = try allocator.dupe(u8, "Author"),
            .date = null,
            .theme = null,
        },
        .slides = try allocator.alloc(Slide, 1),
    };
    defer {
        presentation.metadata.deinit(allocator);
        for (presentation.slides) |slide| {
            slide.deinit(allocator);
        }
        allocator.free(presentation.slides);
    }

    var elements: std.ArrayList(Element) = .empty;
    defer elements.deinit(allocator);

    const heading_content = try allocator.alloc(@import("../core/Element.zig").Inline, 1);
    heading_content[0] = .{ .text = try allocator.dupe(u8, "Test") };

    try elements.append(allocator, .{ .heading = .{
        .content = heading_content,
        .level = 1,
    } });

    presentation.slides[0] = Slide{
        .elements = try elements.toOwnedSlice(allocator),
        .speaker_notes = null,
    };

    var exporter = BeamerExporter.init(allocator, null, null);
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    // Check special characters are escaped
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\$100"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\&"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\%"));
}

test "BeamerExporter inline formatting" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "Formatting Test"),
            .author = try allocator.dupe(u8, "Author"),
            .date = null,
            .theme = null,
        },
        .slides = try allocator.alloc(Slide, 1),
    };
    defer {
        presentation.metadata.deinit(allocator);
        for (presentation.slides) |slide| {
            slide.deinit(allocator);
        }
        allocator.free(presentation.slides);
    }

    var elements: std.ArrayList(Element) = .empty;
    defer elements.deinit(allocator);

    // Create paragraph with bold and italic text
    const para_content = try allocator.alloc(@import("../core/Element.zig").Inline, 3);
    para_content[0] = .{ .text = try allocator.dupe(u8, "Normal ") };
    const bold_content = try allocator.alloc(@import("../core/Element.zig").Inline, 1);
    bold_content[0] = .{ .text = try allocator.dupe(u8, "bold") };
    para_content[1] = .{ .bold = bold_content };
    para_content[2] = .{ .text = try allocator.dupe(u8, " text") };

    try elements.append(allocator, .{ .paragraph = .{
        .content = para_content,
    } });

    presentation.slides[0] = Slide{
        .elements = try elements.toOwnedSlice(allocator),
        .speaker_notes = null,
    };

    var exporter = BeamerExporter.init(allocator, null, null);
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    // Check formatting commands
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\textbf{bold}"));
}

test "BeamerExporter code block" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "Code Test"),
            .author = try allocator.dupe(u8, "Author"),
            .date = null,
            .theme = null,
        },
        .slides = try allocator.alloc(Slide, 1),
    };
    defer {
        presentation.metadata.deinit(allocator);
        for (presentation.slides) |slide| {
            slide.deinit(allocator);
        }
        allocator.free(presentation.slides);
    }

    var elements: std.ArrayList(Element) = .empty;
    defer elements.deinit(allocator);

    try elements.append(allocator, .{ .code_block = .{
        .language = try allocator.dupe(u8, "python"),
        .code = try allocator.dupe(u8, "print('hello')"),
    } });

    presentation.slides[0] = Slide{
        .elements = try elements.toOwnedSlice(allocator),
        .speaker_notes = null,
    };

    var exporter = BeamerExporter.init(allocator, null, null);
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\begin{lstlisting}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "print('hello')"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\end{lstlisting}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "language=Python"));
}

test "BeamerExporter list" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "List Test"),
            .author = try allocator.dupe(u8, "Author"),
            .date = null,
            .theme = null,
        },
        .slides = try allocator.alloc(Slide, 1),
    };
    defer {
        presentation.metadata.deinit(allocator);
        for (presentation.slides) |slide| {
            slide.deinit(allocator);
        }
        allocator.free(presentation.slides);
    }

    var elements: std.ArrayList(Element) = .empty;
    defer elements.deinit(allocator);

    // Create unordered list
    var items = try allocator.alloc(@import("../core/Element.zig").ListItem, 2);
    const item1_content = try allocator.alloc(@import("../core/Element.zig").Inline, 1);
    item1_content[0] = .{ .text = try allocator.dupe(u8, "First item") };
    items[0] = .{ .content = item1_content, .children = null };

    const item2_content = try allocator.alloc(@import("../core/Element.zig").Inline, 1);
    item2_content[0] = .{ .text = try allocator.dupe(u8, "Second item") };
    items[1] = .{ .content = item2_content, .children = null };

    try elements.append(allocator, .{ .list = .{
        .ordered = false,
        .items = items,
    } });

    presentation.slides[0] = Slide{
        .elements = try elements.toOwnedSlice(allocator),
        .speaker_notes = null,
    };

    var exporter = BeamerExporter.init(allocator, null, null);
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\begin{itemize}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\item First item"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\item Second item"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\end{itemize}"));
}

test "BeamerExporter theme selection" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var presentation = Presentation{
        .allocator = allocator,
        .metadata = .{
            .title = try allocator.dupe(u8, "Theme Test"),
            .author = try allocator.dupe(u8, "Author"),
            .date = null,
            .theme = null,
        },
        .slides = &.{},
    };
    defer {
        presentation.metadata.deinit(allocator);
        allocator.free(presentation.slides);
    }

    var exporter = BeamerExporter.init(allocator, "metropolis", "crane");
    const latex = try exporter.exportToLatex(presentation);
    defer allocator.free(latex);

    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\usetheme{metropolis}"));
    try testing.expect(std.mem.containsAtLeast(u8, latex, 1, "\\usecolortheme{crane}"));
}
